/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package userInterface;

import helppage.HelpPage;
import helppage.HelpPage;
import java.io.FileNotFoundException;
import java.util.logging.Level;
import java.util.logging.Logger;
import startJpanelUI.StartJPanel;

/**
 *
 * @author Samsung
 */
public class IS3SystemUI extends javax.swing.JFrame {

    private StartJPanel sp;
    
    public IS3SystemUI() throws FileNotFoundException {
        initComponents();
        
        sp = new StartJPanel(this);
        sp.setBounds(0, 0, (int)sp.getPreferredSize().getWidth(), (int)sp.getPreferredSize().getHeight());
        sp.setVisible(true);
        
        this.getContentPane().add(sp);
        this.pack();
        // The frame does not resize when using pack(). It should resize based on the preferredSize of MainPagePanel
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAlwaysOnTop(true);
        setMaximizedBounds(new java.awt.Rectangle(0, 0, 1000, 1000));
        getContentPane().setLayout(new java.awt.GridBagLayout());

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(IS3SystemUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(IS3SystemUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(IS3SystemUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(IS3SystemUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                IS3SystemUI theSystem;
                try {
                    theSystem = new IS3SystemUI();
                    theSystem.setVisible(true);
                } catch (FileNotFoundException ex) {
                    Logger.getLogger(IS3SystemUI.class.getName()).log(Level.SEVERE, null, ex);
                }
            }// end of run
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
